server.port=8081

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/shortener_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/shortener_db

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Thread Pool Configuration for @Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=AsyncApp-
